export { default as Navigation } from "./Navigation";
export { default as Footer } from "./Footer";
export { default as Home } from "./Home";
export { default as About } from "./About";
export { default as Contact } from "./Contact";
export { default as Portfolio } from "./Portfolio";
export { default as Digital } from "./Digital";
export { default as SmallPrint } from "./SmallPrint";
export { default as LargePrint } from "./LargePrint";